/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementoop;

//import hotelmanagementoop.tripstay;
//import hotelmanagementoop.weddingBook;
//import hotelmanagementoop.globalname;
//import hotelmanagementoop.onlyfood;
//import hotelmanagementoop.onlyfood.price;


import java.io.*;
/**
 *
 * @author shiva
 */
public class Billling extends javax.swing.JFrame {
    String bill;
    /**
     * Creates new form Billling
     */
    public Billling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        orderFood = new javax.swing.JLabel();
        ViewFoodMenu1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        for_food_menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myArea = new javax.swing.JTextArea();
        printlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        orderFood.setBackground(new java.awt.Color(0, 0, 0));
        orderFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderFood.setForeground(new java.awt.Color(255, 255, 255));
        orderFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderFood.setText("Print Receipt");
        orderFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        orderFood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderFoodMouseClicked(evt);
            }
        });

        ViewFoodMenu1.setBackground(new java.awt.Color(0, 0, 0));
        ViewFoodMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewFoodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        ViewFoodMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewFoodMenu1.setText("Bill receipt");
        ViewFoodMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        ViewFoodMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFoodMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFoodMenu1MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewFoodMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(orderFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(ViewFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(orderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(36, 36, 36))
        );

        for_food_menu.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        myArea.setColumns(20);
        myArea.setRows(5);
        jScrollPane1.setViewportView(myArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        printlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printlabel.setForeground(new java.awt.Color(0, 255, 0));
        printlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printlabel.setText("Your bill is ready.");

        javax.swing.GroupLayout for_food_menuLayout = new javax.swing.GroupLayout(for_food_menu);
        for_food_menu.setLayout(for_food_menuLayout);
        for_food_menuLayout.setHorizontalGroup(
            for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_food_menuLayout.createSequentialGroup()
                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(printlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        for_food_menuLayout.setVerticalGroup(
            for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_food_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printlabel)
                .addGap(25, 25, 25))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hamburger-96.png"))); // NOI18N

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("\"Thanks for visiting us.\"");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Billing Counter");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-48.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(for_food_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(49, 49, 49)))
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(379, 379, 379)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(681, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(for_food_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(674, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void orderFoodMouseClicked(java.awt.event.MouseEvent evt){//GEN-FIRST:event_orderFoodMouseClicked
        try{
            String gname = globalname.GlobalName;
            FileWriter finale=new FileWriter("src\\checkoutBill\\"+gname+".txt");
            printBill();
            finale.write(bill);
            printlabel.setText("your bill is in printing process also you can have the text file for the same.");
        }
        catch(IOException e){printlabel.setText("file is being found.");}

    }//GEN-LAST:event_orderFoodMouseClicked
   
    
    
    void printBill(){
        ;
//        onlyfood.price foodbill ;
//        foodbill = new onlyfood.price();
//        weddingBook weddingBk = new weddingBook();
//        weddingBook.weddingbill weddingbill;
//        weddingbill = new weddingBook.weddingbill();
//        tripstay tstay = new tripstay();
//        tripstay.selection roombill;
//        roombill = new tripstay.selection();

        price foodbill = new price();
        weddingbill weddingbill = new weddingbill();
        selection roombill = new selection();
        globalname g = new globalname();
        String gname = g.getGlobalName();
        System.out.println(gname);

        try{

            String account = "src\\roomConfirm\\"+gname+".txt";
            FileInputStream fileA = new FileInputStream(account);
            ObjectInputStream obbA = new ObjectInputStream(fileA);
            System.out.println("hello roomConfirm");
            try{
                roombill = (selection) obbA.readObject();
            }
            catch(NullPointerException e){
            roombill.DBD = 0;
            roombill.SBD = 0;
            roombill.total = 0;
            }
            System.out.println("hi roomConfirm");
            System.out.println(roombill.SBD);
            System.out.println(roombill.DBD);
            obbA.close();
            fileA.close();
        }
        catch(NullPointerException|IOException|ClassNotFoundException e){
            
            System.out.println("error roomconfirm or no roomconfirmed");
           
        }

        try{

            String account = "src\\hall\\"+gname+".txt";
            FileInputStream fileB = new FileInputStream(account);
            ObjectInputStream obbB = new ObjectInputStream(fileB);
            try{
                weddingbill =(weddingbill)obbB.readObject();
            }
            catch(NullPointerException e){
            weddingbill.AC = 0;
            weddingbill.nonAC = 0;
            weddingbill.total = 0;
            }
            System.out.println("hi weddingbill");
            obbB.close();
            fileB.close();
        }
        catch(NullPointerException|IOException|ClassNotFoundException e){
            System.out.println("error weddingbill or no hall booked");
            
        }

        try{

            String account = "src\\food\\"+gname+".txt";
            FileInputStream fileC = new FileInputStream(account);
            ObjectInputStream obbC = new ObjectInputStream(fileC);
            try{
                foodbill =(price)obbC.readObject();
            }
            catch(NullPointerException e){
                foodbill.BM = 0;
            foodbill.JR = 0;
            foodbill.PB = 0;
            foodbill.roti=0;
            foodbill.total=0;
            }
            System.out.println(foodbill);
            System.out.println("hi foodbill");
            obbC.close();
            fileC.close();
            
        }
        catch(NullPointerException|IOException|ClassNotFoundException e){
            System.out.println("error foodbill");
            
        }
        

        String noButterRoti = Integer.toString(foodbill.getRoti());
        String noPaneerBhurji = Integer.toString(foodbill.getPB());
        String noButterMilk = Integer.toString(foodbill.getBM());
        String noJeeraRice = Integer.toString(foodbill.getJR());
        int finalTotal = foodbill.total + weddingbill.getTotal() + roombill.total;
        String myBillText ="***************************************************************\n"
                + "                                 MAHARAJA INN                               "
                + "\n------------------------------------------------------------------------"
                + "\n------------------------------------------------------------------------"
                + "\n                              ROOM DETAILS                                 "
                
                
                + "\nNO      TYPE                                  QTY              PRICE"
                + "\n  1    SINGLE-BED ROOM            "+roombill.SBD+"               3000"
                + "\n  2   DOUBLE-BED ROOM          "+roombill.DBD+"               5000"
                + "\n            TOTAL                                                    "+roombill.total
                + "\n\n------------------------------------------------------------------------"
                + "\n                              HALL DETAILS                                 "
                + "\n\n        BOOKED(YES/NO)                QTY         PRICE"
                + "\n          AC                                            "+weddingbill.AC+"           20000"
                + "\n          non-AC                                        "+weddingbill.nonAC+"          10000"
                + "\n------------------------------------------------------------------------"
                + "\n  FOOD DETAILS(SERVICE/RESTAURANT)                                 "
                + "\n"
                + "\nNO      TYPE                                  QTY          PRICE"
                + "\n1     BUTTER ROTI                        "+noButterRoti+"               "+foodbill.getRoti()*15
                + "\n2     PANEER BHURJI                   "+noPaneerBhurji+"              "+foodbill.getPB()*125
                + "\n3     BUTTER MILK                         "+noButterMilk+"              "+foodbill.getBM()*15
                + "\n4     JEERA RICE                           "+noJeeraRice+"               "+foodbill.getJR()*80
                + "\n            TOTAL                                                 "+foodbill.getTotal()
                + "\n------------------------------------------------------------------------"
                + "\n------------------------------------------------------------------------"
                + "\n                              TOTAL PAYMENT                                "
                + "\n                              TOTAL = "+Integer.toString(finalTotal)+"                                "
                + "\n------------------------------------------------------------------------"
                + "\n------------------------------------------------------------------------"
                + "\n                          THANKYOU FOR VISIT                             "
                + "\n------------------------------------------------------------------------"
                + "\n**************************************************************";
        
            
        bill = myBillText;
        myArea.setText(myBillText);
    }

    private void ViewFoodMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFoodMenu1MouseClicked
        
        
        printBill();
        // delete account same name.
    }//GEN-LAST:event_ViewFoodMenu1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Billling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewFoodMenu1;
    private javax.swing.JPanel for_food_menu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea myArea;
    private javax.swing.JLabel orderFood;
    private javax.swing.JLabel printlabel;
    // End of variables declaration//GEN-END:variables
}
