/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementoop;
import hotelmanagementoop.globalname;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;

/**
 *
 * @author shiva
 */

interface foodPrice{
    public int getRoti();
    public void setRoti(int roti);
     public int getPB();
     public void setPB(int PB);
     public int getBM();
     public void setBM(int BM);
     public int getJR();
     public void setJR(int JR);
     public int getTotal();
     
     
     
    
    
}

class price implements Serializable , foodPrice
{
        int roti;
        int PB;
        int BM;
        int JR;
        int total=0;
        public int getRoti(){
            return roti;
        }
        public void setRoti(int roti){
            this.roti=roti;
            this.total += 15 * roti;
        }
        public int getPB(){
            return PB;
        }
        public void setPB(int PB){
            this.PB=PB;
            this.total += 125*PB;
        }
        public int getBM(){
            return BM;
        }
        public void setBM(int BM){
            this.BM=BM;
            this.total += 15*BM;
        }
        public int getJR(){
            return JR;
        }
        public void setJR(int JR){
            this.JR=JR;
            this.total += JR*80;
        }
        public int getTotal(){
            return this.total;
        }
        

    }
public class onlyfood extends javax.swing.JFrame {

    /**
     * Creates new form onlyfood
     */
    public onlyfood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        confirmorder = new javax.swing.JButton();
        orderFood = new javax.swing.JLabel();
        ViewFoodMenu1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        for_food_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        butterroti = new javax.swing.JTextField();
        buttermilk = new javax.swing.JTextField();
        jeerarice = new javax.swing.JTextField();
        paneerbhurji = new javax.swing.JTextField();
        br = new javax.swing.JCheckBox();
        jr = new javax.swing.JCheckBox();
        bm = new javax.swing.JCheckBox();
        pb = new javax.swing.JCheckBox();
        total = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        confirmorder.setBackground(new java.awt.Color(153, 255, 255));
        confirmorder.setText("confirm order");
        confirmorder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmorderMouseClicked(evt);
            }
        });

        orderFood.setBackground(new java.awt.Color(0, 0, 0));
        orderFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderFood.setForeground(new java.awt.Color(255, 255, 255));
        orderFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderFood.setText("ORDER FOOD");
        orderFood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        orderFood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderFoodMouseClicked(evt);
            }
        });

        ViewFoodMenu1.setBackground(new java.awt.Color(0, 0, 0));
        ViewFoodMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewFoodMenu1.setForeground(new java.awt.Color(255, 255, 255));
        ViewFoodMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewFoodMenu1.setText("VIEW FOOD MENU");
        ViewFoodMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        ViewFoodMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFoodMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFoodMenu1MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewFoodMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(orderFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ViewFoodMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(confirmorder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(36, 36, 36))
        );

        for_food_menu.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUTTER ROTI");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BUTTER MILK");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JEERA RICE");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PANEER BHURJI");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        butterroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterrotiActionPerformed(evt);
            }
        });

        buttermilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttermilkActionPerformed(evt);
            }
        });

        jeerarice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeerariceActionPerformed(evt);
            }
        });

        paneerbhurji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneerbhurjiActionPerformed(evt);
            }
        });

        br.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        br.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        br.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brStateChanged(evt);
            }
        });
        br.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brMouseClicked(evt);
            }
        });

        jr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jrStateChanged(evt);
            }
        });
        jr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrMouseClicked(evt);
            }
        });

        bm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bmStateChanged(evt);
            }
        });
        bm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmMouseClicked(evt);
            }
        });

        pb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbStateChanged(evt);
            }
        });
        pb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbMouseClicked(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(51, 255, 0));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("Total");

        javax.swing.GroupLayout for_food_menuLayout = new javax.swing.GroupLayout(for_food_menu);
        for_food_menu.setLayout(for_food_menuLayout);
        for_food_menuLayout.setHorizontalGroup(
            for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_food_menuLayout.createSequentialGroup()
                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(for_food_menuLayout.createSequentialGroup()
                                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttermilk, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jeerarice, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(for_food_menuLayout.createSequentialGroup()
                                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butterroti, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paneerbhurji, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        for_food_menuLayout.setVerticalGroup(
            for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(for_food_menuLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butterroti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneerbhurji, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jeerarice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(for_food_menuLayout.createSequentialGroup()
                        .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, for_food_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttermilk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hamburger-96.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restaurant");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("\"Your happiness is our first priority\"");

        goback.setBackground(new java.awt.Color(0, 0, 0));
        goback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        goback.setForeground(new java.awt.Color(255, 255, 255));
        goback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-48.png"))); // NOI18N
        goback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        goback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(for_food_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGap(116, 116, 116)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel24)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(for_food_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butterrotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterrotiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butterrotiActionPerformed

    private void buttermilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttermilkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttermilkActionPerformed

    private void jeerariceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeerariceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeerariceActionPerformed

    private void paneerbhurjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneerbhurjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneerbhurjiActionPerformed

    private void confirmorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmorderMouseClicked
        // TODO add your handling code here:
        total.setText("your order has been queued.");
        try{Thread.sleep(2000);}
        catch(Exception e){}
        total.setText("order confirmed");
        try{Thread.sleep(2000);}
        catch(Exception e){}
        total.setText("Your patience will be served with great taste.");
         try{
             String gname = globalname.GlobalName;
//             SignInObjectmaker s= new SignInObjectmaker();
            String account = "src\\food\\"+gname+".txt";
            FileOutputStream fileO = new FileOutputStream(account);
            ObjectOutputStream obb = new ObjectOutputStream(fileO);
            
             
            System.out.println(price);
            obb.writeObject(price);
            
            obb.close();
            fileO.close();
             
        }
            catch(IOException e){
            
             total.setText("SOMETHING WENT WRONG PLEASE LOGIN AGAIN");
            }
         new HMselection().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_confirmorderMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void orderFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderFoodMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_orderFoodMouseClicked

    private void ViewFoodMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFoodMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewFoodMenu1MouseClicked

    private void brMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseClicked
        if(br.isSelected()){
            price.setRoti(Integer.valueOf(butterroti.getText()));
        }
        else{
            if(butterroti.getText() != ""){
                price.total -= 15*Integer.valueOf(butterroti.getText());
            }
        }
        total.setText("Rs. "+price.total);
        
    }//GEN-LAST:event_brMouseClicked

    private void pbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseClicked
        if(pb.isSelected()){

            price.setPB(Integer.valueOf(paneerbhurji.getText()));

        }
        else{
            if(paneerbhurji.getText() != ""){
                price.total -= 125*Integer.valueOf(paneerbhurji.getText());
            }

        }
        total.setText("Rs. "+price.total);

    }//GEN-LAST:event_pbMouseClicked

    private void jrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrMouseClicked
        // TODO add your handling code here:
        if(jr.isSelected()){

            price.setJR(Integer.valueOf(jeerarice.getText()));

        }
        else{
            if(jeerarice.getText() != ""){
                price.total -= 80*Integer.valueOf(jeerarice.getText());
            }

        }
        total.setText("Rs. "+price.total);
    }//GEN-LAST:event_jrMouseClicked

    private void bmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmMouseClicked
        // TODO add your handling code here:
        if(bm.isSelected()){

            price.setBM(Integer.valueOf(buttermilk.getText()));

        }
        else{
            if(buttermilk.getText()!=""){
                price.total -= 15*Integer.valueOf(buttermilk.getText());
            }
            

        }
        total.setText("Rs. "+price.total);
    }//GEN-LAST:event_bmMouseClicked
    price price = new price();
    private void brStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_brStateChanged

    private void pbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbStateChanged

    }//GEN-LAST:event_pbStateChanged

    private void jrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jrStateChanged

    }//GEN-LAST:event_jrStateChanged

    private void bmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bmStateChanged
            }//GEN-LAST:event_bmStateChanged

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        // TODO add your handling code here:
        new HMselection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(onlyfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(onlyfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(onlyfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(onlyfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new onlyfood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewFoodMenu1;
    private javax.swing.JCheckBox bm;
    private javax.swing.JCheckBox br;
    private javax.swing.JTextField buttermilk;
    private javax.swing.JTextField butterroti;
    private javax.swing.JButton confirmorder;
    private javax.swing.JPanel for_food_menu;
    private javax.swing.JLabel goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jeerarice;
    private javax.swing.JCheckBox jr;
    private javax.swing.JLabel orderFood;
    private javax.swing.JTextField paneerbhurji;
    private javax.swing.JCheckBox pb;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
